//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum ProjectRole { 
	Head = 0, 
	Executor = 1, 
	Tester = 2, 
	Developer = 3
}
