//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum Role { 
	Administrator = 0, 
	Developer = 1, 
	Tester = 2, 
	Marketolog = 3, 
	Accounter = 4
}
