//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum SubtaskType { 
	InsertWordsIntoGaps = 0, 
	FillGaps = 1, 
	RightVerbForm = 2, 
	LoadAudio = 3, 
	DetailedAnswer = 4, 
	LoadFile = 5
}
