//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum WordTrainingType { 
	LearnNew = 0, 
	Repeat = 1
}
