//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { ProjectViewModel } from './ProjectViewModel';
import { UserViewModel } from './UserViewModel';
import { ProjectRole } from '../enums/ProjectRole';

export class ProjectUserViewModel
{
	public project: ProjectViewModel;
	public user: UserViewModel;
	public role: ProjectRole;
}
