//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Role } from '../enums/Role';

export class UserReadModel
{
	public id: number;
	public firstName: string;
	public lastName: string;
	public email: string;
	public password: string;
	public role: Role;
}
