//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class FeedbackReadModel
{
	public id: number;
	public name: string;
	public email: string;
	public message: string;
	public old: boolean;
}
