//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { TaskType } from '../enums/TaskType';
import { TaskStatus } from '../enums/TaskStatus';
import { TaskPriority } from '../enums/TaskPriority';

export interface ITaskReadModel
{
	id: number;
	projectId: number;
	header: string;
	description: string;
	startDate: any;
	deadlineDate: any;
	taskType: TaskType;
	status: TaskStatus;
	priority: TaskPriority;
	tester: number;
	responsible: number;
	author: number;
}
