//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { ITaskReadModel } from './ITaskReadModel';
import { TaskRole } from '../enums/TaskRole';

export interface IUserTaskReadModel
{
	user: IUserTaskReadModel;
	task: ITaskReadModel;
	role: TaskRole;
}
