//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class LessonReadModel
{
	public id: number;
	public order: number;
	public courseId: number;
	public name: string;
	public description: string;
	public startDate: any;
	public expireDate: any;
}
