//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { LessonReadModel } from './LessonReadModel';

export class LessonsCollectionReadModel
{
	public lessons: LessonReadModel[];
	public courseId: number;
}
