//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { SubtaskReadModel } from './SubtaskReadModel';
import { TagReadModel } from './TagReadModel';

export class TaskReadModel
{
	public id: number;
	public instruction: string;
	public text: string;
	public subtasks: SubtaskReadModel[];
	public tags: TagReadModel[];
}
