//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { TaskType } from '../enums/TaskType';
import { SubtaskReadModel } from './SubtaskReadModel';

export class TaskReadModel
{
	public id: number;
	public instruction: string;
	public text: string;
	public lessonId: number;
	public order: number;
	public taskType: TaskType;
	public subtasks: SubtaskReadModel[];
	public tagIds: number[];
	public subtagIds: number[];
	public deleteOnlyFromLesson: boolean;
}
