//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { TrackerByDayReadModel } from './TrackerByDayReadModel';

export class TrackerReadModel
{
	public id: number;
	public userId: number;
	public courseId: number;
	public trackersByDay: TrackerByDayReadModel[];
}
