//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class TrackerByDayReadModel
{
	public id: number;
	public vebinarWatch: boolean;
	public completedHomework: boolean;
	public dictionaryOfLesson: boolean;
	public wordOfADay: boolean;
	public chatParticipation: boolean;
	public day: number;
}
