//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { CompletingStatus } from '../enums/CompletingStatus';

export class UserSubtaskAnswerGroupReadModel
{
	public userId: number;
	public answerGroupId: number;
	public subtaskId: number;
	public status: CompletingStatus;
	public lastAnswer: string;
}
