//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class UserNotificationReadModel
{
	public userId: number;
	public notificationId: number;
	public seen: boolean;
}
