//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { WordReadModel } from './WordReadModel';
import { CompletingStatus } from '../enums/CompletingStatus';

export class UserWordReadModel
{
	public userId: number;
	public word: WordReadModel;
	public countOfAttempts: number;
	public rightAnswers: number;
	public status: CompletingStatus;
	public answer: string;
}
