//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { WordReadModel } from './WordReadModel';

export class WordOfADayReadModel
{
	public date: any;
	public word: WordReadModel;
	public courseId: number;
}
