//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { TaskViewModel } from './TaskViewModel';
import { TaskRole } from '../enums/TaskRole';

export class UserTaskViewModel
{
	public user: UserTaskViewModel;
	public task: TaskViewModel;
	public role: TaskRole;
}
