//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { UserViewModel } from './UserViewModel';
import { ProjectViewModel } from './ProjectViewModel';
import { ProjectUserViewModel } from './ProjectUserViewModel';
import { ProjectTaskViewModel } from './ProjectTaskViewModel';
import { TaskViewModel } from './TaskViewModel';
import { UserTaskViewModel } from './UserTaskViewModel';
import { CommentGroupViewModel } from './CommentGroupViewModel';

export class CommonViewModel
{
	public user: UserViewModel;
	public projects: ProjectViewModel[] = [];
	public projectUsers: ProjectUserViewModel[] = [];
	public projectTasks: ProjectTaskViewModel[] = [];
	public tasks: TaskViewModel[] = [];
	public userTasks: UserTaskViewModel[] = [];
	public users: UserViewModel[] = [];
	public commentGroups: CommentGroupViewModel[] = [];
}
