//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class CommentViewModel
{
	public id: number;
	public userId: number;
	public text: string;
	public publishDate: any;
}
