//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { CommentViewModel } from './CommentViewModel';

export class CommentGroupViewModel
{
	public id: number;
	public commentedEntityType: string;
	public commentedEntityId: number;
	public userId: number;
	public comments: CommentViewModel[] = [];
}
