//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class ProjectViewModel
{
	public id: number;
	public name: string;
	public description: string;
	public startDate: any;
	public deadlineDate: any;
	public responsiblePerson: number;
}
