//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class SubtaskAnswerViewModel
{
	public id: number;
	public answer: string;
	public isRight: boolean;
	public isInfinitive: boolean;
	public explanation: string;
}
