//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { SubtagViewModel } from './SubtagViewModel';

export class TagViewModel
{
	public id: number;
	public name: string;
	public subtags: SubtagViewModel[] = [];
}
