//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { TaskType } from '../enums/TaskType';
import { TaskStatus } from '../enums/TaskStatus';
import { TaskPriority } from '../enums/TaskPriority';

export class TaskViewModel
{
	public id: number;
	public header: string;
	public description: string;
	public startDate: any;
	public deadlineDate: any;
	public taskType: TaskType;
	public status: TaskStatus;
	public priority: TaskPriority;
}
