//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { CompletingStatus } from '../enums/CompletingStatus';
import { UserSubtaskAnswerGroupViewModel } from './UserSubtaskAnswerGroupViewModel';

export class UserSubtaskViewModel
{
	public status: CompletingStatus;
	public answer: string;
	public subtaskId: number;
	public answerFiles: string[] = [];
	public userSubtaskAnswerGroups: UserSubtaskAnswerGroupViewModel[] = [];
}
