//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { CompletingStatus } from '../enums/CompletingStatus';

export class UserWordViewModel
{
	public userId: number;
	public wordId: number;
	public countOfAttempts: number;
	public rightAnswers: number;
	public status: CompletingStatus;
	public answer: string;
}
