//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { PartOfSpeech } from '../enums/PartOfSpeech';

export class WordViewModel
{
	public id: number;
	public word: string;
	public englishMeaning: string;
	public russianMeaning: string;
	public partOfSpeech: PartOfSpeech;
	public examples: any[] = [];
}
